version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./etc/nginx/default.conf.nginx:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    depends_on:
      - backend
      - frontend
      - mysql
    networks:
      - main

  backend:
    build:
      context: etc/backend
    container_name: backend
    volumes:
      - ./backend:/app
      - ./etc/php:/usr/local/etc/php/local.conf.d/
    ports: 
      - 8080:8080
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"
    networks:
      - main

  frontend:
    image: node:16-alpine
    container_name: frontend
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports: 
      - 8000:8000
    environment:
      NODE_ENV: development
    command: "npm run serve -- --port 8000"
    networks:
      - main

  mysql:
    image: mysql:5.7.38
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: floraqueen
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
    networks:
      - main

networks:
  main:
    driver: "bridge"